[package]
name = "pmaxx"
version.workspace = true
edition.workspace = true
description = "CLI to list saved prompts"

[[bin]]
name = "pmaxx"
path = "src/main.rs"

[dependencies]
promptmaxx-core = { workspace = true }
